name: final_project
description: "Articles - Social Media."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.2.2
  socket_io_client: ^3.1.2
  image_picker: ^1.1.0
  dio: ^5.3.2
  video_player: ^2.8.3
  http_parser: ^4.0.2
  flutter_svg: ^2.0.7
  carousel_slider: ^5.1.1
  cached_network_image: ^3.3.0
  emoji_picker_flutter: ^4.3.0
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  chewie: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.7
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_start.png"